### ISSUE TITLE
npm start fails with XAMPP on Windows 10

### ISSUE THREAD

**Issue by likethegoddess** [ahmadawais/WPGulp#152]
### Expected Behavior

Expect that `npm start` in PowerShell within the theme directory to prepare WPGulp to compile Sass. 

### Actual Behavior

`npm start` received the following error message: 

`> your-project@1.0.0 start C:\xampp\htdocs\likethegoddess\wp-content\themes\likethegoddess
> gulp

assert.js:339
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (C:\xampp\htdocs\likethegoddess\wp-content\themes\likethegoddess\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (C:\xampp\htdocs\likethegoddess\wp-content\themes\likethegoddess\node_modules\undertaker\lib\task.js:13
:8)
    at Object.<anonymous> (C:\xampp\htdocs\likethegoddess\wp-content\themes\likethegoddess\gulpfile.js:319:7)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at execute (C:\xampp\htdocs\likethegoddess\wp-content\themes\likethegoddess\node_modules\gulp\node_modules\gulp-cli\
lib\versioned\^4.0.0\index.js:36:18)
    at Liftoff.handleArguments (C:\xampp\htdocs\likethegoddess\wp-content\themes\likethegoddess\node_modules\gulp\node_m
odules\gulp-cli\index.js:201:24)
    at Liftoff.execute (C:\xampp\htdocs\likethegoddess\wp-content\themes\likethegoddess\node_modules\liftoff\index.js:20
1:12)
    at module.exports (C:\xampp\htdocs\likethegoddess\wp-content\themes\likethegoddess\node_modules\flagged-respawn\inde
x.js:51:3)
    at Liftoff.<anonymous> (C:\xampp\htdocs\likethegoddess\wp-content\themes\likethegoddess\node_modules\liftoff\index.j
s:191:5)
    at C:\xampp\htdocs\likethegoddess\wp-content\themes\likethegoddess\node_modules\liftoff\index.js:149:9
    at C:\xampp\htdocs\likethegoddess\wp-content\themes\likethegoddess\node_modules\v8flags\index.js:121:14
    at C:\xampp\htdocs\likethegoddess\wp-content\themes\likethegoddess\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! your-project@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the your-project@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\liket\AppData\Roaming\npm-cache\_logs\2019-07-22T22_18_25_867Z-debug.log`

Debug log: 
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle your-project@1.0.0~prestart: your-project@1.0.0
6 info lifecycle your-project@1.0.0~start: your-project@1.0.0
7 verbose lifecycle your-project@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle your-project@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\xampp\htdocs\likethegoddess\wp-content\themes\likethegoddess\node_modules\.bin;C:\Program Files\PuTTY\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\nodejs\;c:\Program Files\dart-sass;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Ruby24-x64\bin;C:\Users\liket\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Usersx\liket\AppData\Local\GitHubDesktop\bin;C:\Windows\System32;C:\Users\liket\AppData\Roaming\npm
9 verbose lifecycle your-project@1.0.0~start: CWD: C:\xampp\htdocs\likethegoddess\wp-content\themes\likethegoddess
10 silly lifecycle your-project@1.0.0~start: Args: [ '/d /s /c', 'gulp' ]
11 silly lifecycle your-project@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle your-project@1.0.0~start: Failed to exec start script
13 verbose stack Error: your-project@1.0.0 start: `gulp`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid your-project@1.0.0
15 verbose cwd C:\xampp\htdocs\likethegoddess\wp-content\themes\likethegoddess
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error your-project@1.0.0 start: `gulp`
22 error Exit status 1
23 error Failed at the your-project@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]`
 
### Steps to Reproduce

1. Start Apache and MySQL in XAMPP (v3.2.2)
2. Go to theme directory in PowerShell
3. Type `npm start` 

1. `node -v`: v10.16.0
2. `npm -v`: 6.9.0
3. `yarn --version` (if you use Yarn): 

Then, specify:

1. Operating system: Windows 10 Pro, v1803
2. Browser and version (if relevant): 

**Possible Solution**

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by davision** [comment]
Same issue here on Mac.

**Comment by MusharafShafiq** [comment]
i needed a npm assess  how this is managed
