### ISSUE TITLE
WPGulp update failed ( 404 error )

### ISSUE THREAD

**Issue by DarkChris86** [ahmadawais/WPGulp#194]
### Expected Behavior

Update existing workflow.

(Write what you thought would happen.)

### Actual Behavior
After run npx install-wpgulp I got this:
GotError [HTTPError]: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (C:\Users\...\AppData\Roaming\npm-cache\_npx\1976\node_modules\install-wpgulp\node_modules\got\index.js:482:24)
    at EventEmitter.emit (events.js:311:20)
    at getResponse (C:\Users\...\AppData\Roaming\npm-cache\_npx\1976\node_modules\install-wpgulp\node_modules\got\index.js:320:5)
    at Immediate.<anonymous> (C:\Users\...\AppData\Roaming\npm-cache\_npx\1976\node_modules\install-wpgulp\node_modules\got\index.js:147:6)
    at processImmediate (internal/timers.js:456:21) {
  name: 'HTTPError',
  host: 'raw.githubusercontent.com',
  hostname: 'raw.githubusercontent.com',
  method: 'GET',
  path: '/ahmadawais/WPGulp/master/src/package.json',
  protocol: 'https:',
  url: 'https://raw.githubusercontent.com/ahmadawais/WPGulp/master/src/package.json',
  statusCode: 404,
  statusMessage: 'Not Found',
  headers: {
    connection: 'close',
    'content-length': '14',
    'content-type': 'text/plain; charset=utf-8',
    'content-security-policy': "default-src 'none'; style-src 'unsafe-inline'; sandbox",
    'strict-transport-security': 'max-age=31536000',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-xss-protection': '1; mode=block',
    via: '1.1 varnish (Varnish/6.0), 1.1 varnish',
    'x-github-request-id': '6EE0:FA8B:32284F3:3508610:5F982C85',
    'accept-ranges': 'bytes',
    date: 'Tue, 27 Oct 2020 14:19:49 GMT',
    'x-served-by': 'cache-hhn4063-HHN',
    'x-cache': 'HIT, MISS',
    'x-cache-hits': '1, 0',
    'x-timer': 'S1603808390.773020,VS0,VE93',
    vary: 'Authorization,Accept-Encoding',
    'access-control-allow-origin': '*',
    'x-fastly-request-id': '2cb669584d8737c11510c5e854354998594ff69c',
    expires: 'Tue, 27 Oct 2020 14:24:49 GMT',
    'source-age': '0'
  }
}

(Write what happened. Please add screenshots!)

### Steps to Reproduce

1. Run npx install-wpgulp on existing setup

**Possible Solution**

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by DeoThemes** [comment]
Something is wrong with the latest release. There is supposed to be Gulp Zip task, but it's never defined in the [gulpfile.babel,js](https://github.com/ahmadawais/WPGulp/blob/master/WPGulp/gulpfile.babel.js)

**Comment by DarkChris86** [comment]
Okay I found out.

The _npx install-wpgulp_ no more works.
It should be only this: **npx wpgulp** and now works fine.
